### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by ghost** [YSpoof/mindustry-zmod#1]
![Screenshot_2021-05-16-11-35-31-78_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/84266627/118391165-94296a80-b63b-11eb-8140-96e5e94687e9.jpg)
The mod is awesome but there is one issue the time speed interface is covering the flip ui which kinda breaks the game

**Comment by YSpoof** [comment]
Thanks for reporting it, since I don't play on mobile, the image helped a lot lol, this should be fixed now, can u try reinstalling the mod ? But I've found another one, if u press the "copy button", I'm working on a fix for the second one.
