### ISSUE TITLE
Hi again 

### ISSUE THREAD

**Issue by ghost** [YSpoof/mindustry-zmod#2]
![Screenshot_2021-05-16-15-22-00-97_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/84266627/118397192-85eb4680-b65b-11eb-96c4-5850102a1d4f.jpg)
Thanks for responding so quickly but still the same issue even after re installing it

**Comment by YSpoof** [comment]
@kuraisensei9099 uninstall the mod, restart the game, go to mods, import from git, and type: YSpoof/mindustry-zmod

Then ok, then back to restart the game, mod version should be 1.0.3

**Comment by ghost** [comment]
I did all that before and still the same this what it's looks like
![Screenshot_2021-05-16-15-38-54-98_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/84266627/118397608-8d135400-b65d-11eb-85c6-48a1b35b4996.jpg)

**Comment by YSpoof** [comment]
@kuraisensei9099 the mod version is 1.0.3 ?

**Comment by YSpoof** [comment]
Now I c what's happening.... This is the second bug I said ( related to schematic huh ? ), this I'm trying to fix, I fixed another one ( when u build )
@kuraisensei9099

**Comment by ghost** [comment]
Yeah its happens when i open schematics 
But the building one that i never encountered before

**Comment by YSpoof** [comment]
I c, I'm working on a fix for the schematics

**Comment by YSpoof** [comment]
@kuraisensei9099 can u try it again?

**Comment by ghost** [comment]
All good now thanks mate this mod is my top favourite to play the campaign with its a true masterpiece

**Comment by ghost** [comment]
By the way can you add more power items not some op ones but like a wind turbine simple and does not Break the game that will be cool to see because this mod has a very good potential

**Comment by ghost** [comment]
Iam sorry for bothering you but the t_ 35 Sprite is broken now
![Screenshot_2021-05-16-16-41-42-36_13f989b68d7412e5a177fb13b36ac66f](https://user-images.githubusercontent.com/84266627/118399583-86d5a580-b666-11eb-9dc3-fa47fdcf7839.jpg)

**Comment by YSpoof** [comment]
About the Wind Turbine, iirc reVision already has that, and I'm not a Java programmer or Sprite artist :(

About T-34 yeah, I need a sprite for this, if u want to help, here's my Discord: NotZero#4043

**Comment by ghost** [comment]
Iam not an artist myself but i might be able to help you
